import Authprovider from "./(authprovider)/AuthProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>{children}</Authprovider>
      </body>
    </html>
  );
}
